version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: couponSystem
      MYSQL_USER: projectUser
      MYSQL_PASSWORD: projectUser
    ports:
      - '3306:3306'
    volumes:
      - ./couponSystemSchemaToImport.sql:/docker-entrypoint-initdb.d/couponSystemSchemaToImport.sql

  app:
    build: .
    container_name: coupon-system-app
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/couponSystem
      DB_USER: projectUser
      DB_PASSWORD: projectUser
